# Site settings
title: Brussels
description: >
  From the magnificent Grand Place – one of the most beautiful squares in Europe – to the fresh crop of stylish hotels and restaurants, this must-visit city fascinates at every turn.
baseurl: "/brussels" # the subpath of your site, e.g. /blog/
url: "https://www.secretescapes.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, bower_components, bower.json, README.md]
